### ISSUE TITLE
Support legends for custom categories

### ISSUE THREAD

**Issue by otabekgb** [tanganellilore/visavail#1]
Currently it only shows legends for default availability. I should show legends for all.
Actually better refactoring should be to add the categories to options, not in series. and the default  should be the availability

**Comment by tanganellilore** [comment]
Hi @otabekgb,

The custom categories displaied in the tooltip mouse over and We esclude from The Legend because at the moment the custom categories is related to a single Series.

You need to understand the original scope of the Library (data availability in a time range). Other option is for became the Library more customizable and more flexible.

At the moment I think about your request but this type of  enhancement it's not the first priority.

The refactoring of Series i think at the moment it's not possibile but the leged for custom categories I think it's possibile....


Have you any ideas for the layout of custom categories(on top, on bottom etc)

You can share to me some picture.

**Comment by tanganellilore** [comment]
Close this iusse, due any update from 1 month.
