### ISSUE TITLE
Request to pull to flrs/visavail

### ISSUE THREAD

**Issue by flrs** [tanganellilore/visavail#5]
Dear @tanganellilore,

I have checked your progress with the library and I am really impressed by what you have made of it. It looks really good and I really like the features you added. Congratulations!

I think it is a good time for a new release of visavail.js that includes your changes. Would you be interested in creating a pull request of your code to [flrs/visavail](https://github.com/flrs/visavail)? In exchange, I would like to offer you to add your name to the [license](https://github.com/flrs/visavail/blob/master/LICENSE.md) and to distribute the code with your additions on [flrs/visavail](https://github.com/flrs/visavail/releases) as a release. I can also do some testing and documentation, as we discussed a while ago.

Please, let me know what you think!

**Comment by tanganellilore** [comment]
Hi @flrs ,

I'm really happy that you like my work.
I think is the moment to release a new Visavail version 2.0.0, because in my work a rework some part, some aspect and there are some break from your version.

One point, at the moment I released my version also as npm package, for a better import in a node.js application or similar.
We can create an organization in npm repo for manage the library in this way.
Similar for github ( i don't know if for ghitub we have some cost, if there are some costs i can collaborate in your git as developer/release.

I dont' know if this interest you.

**Comment by tanganellilore** [comment]
Hi @flrs,

i create a pull requesto on your repo.
Please add me as dev in our repo to help your work

Thanks
